### ISSUE TITLE
Add validation that makes us of class-validator package

### ISSUE THREAD

**Issue by Tomisiak** [iamclaytonray/nest-graphql-mongodb#5]
In official docs of Nest there is mentioned that pipes together with [class-validator](https://github.com/typestack/class-validator) can be used for validation by adding decorators to DTO class fields. Please provide an example of how we can utilize it with graphql API.

**Comment by iamclaytonray** [comment]
I'm not sure when I can tackle this but it's a great feature request! If I find some time, maybe I'll add this in 😄
