### ISSUE TITLE
array add object

### ISSUE THREAD

**Issue by kuangshp** [iamclaytonray/nest-graphql-mongodb#6]
public async addBookList(_id: String, bookList: IBookList): Promise<IBook> {
    return await this.bookSchema.findByIdAndUpdate({_id}, { $push: { 'bookList': bookList } }).exec();
  }

**Comment by iamclaytonray** [comment]
Can you please add details for a feature or bug that you'd like to report? A block of code doesn't tell me anything

**Comment by iamclaytonray** [comment]
Closing this issue because I can't do anything with this.
